name: 25/7 Consulting
favicon: null
layout_spectrum: 0.13580993935465813
typography_spectrum: 0.8030359644908458
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.7007504659704864
  lightness: 0.9305034331046045
  saturation: 0.15272910986095667
  rhythmicContrast: 0.007389616686850786
purpose: []
